package ParkNPark.interfaces;


/**
* ParkNPark/interfaces/_ReplicationManagerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:36 PM EDT
*/

public class _ReplicationManagerStub extends org.omg.CORBA.portable.ObjectImpl implements ParkNPark.interfaces.ReplicationManager
{

  public void serverRegistered (String ipAddress, String serviceName, ParkNPark.interfaces.ClientManagerFactory cmf)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("serverRegistered", true);
                $out.write_string (ipAddress);
                $out.write_string (serviceName);
                ParkNPark.interfaces.ClientManagerFactoryHelper.write ($out, cmf);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                serverRegistered (ipAddress, serviceName, cmf        );
            } finally {
                _releaseReply ($in);
            }
  } // serverRegistered

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ParkNPark/interfaces/ReplicationManager:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _ReplicationManagerStub
