package ParkNPark.interfaces;


/**
* ParkNPark/interfaces/AlreadyInLotException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:36 PM EDT
*/

public final class AlreadyInLotException extends org.omg.CORBA.UserException
{

  /** The lot that the client is already on */
  public int lot = (int)0;

  public AlreadyInLotException ()
  {
    super(AlreadyInLotExceptionHelper.id());
  } // ctor

  public AlreadyInLotException (int _lot)
  {
    super(AlreadyInLotExceptionHelper.id());
    lot = _lot;
  } // ctor


  public AlreadyInLotException (String $reason, int _lot)
  {
    super(AlreadyInLotExceptionHelper.id() + "  " + $reason);
    lot = _lot;
  } // ctor

} // class AlreadyInLotException
