package ParkNPark.interfaces;

/**
* ParkNPark/interfaces/AlreadyInLotExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:36 PM EDT
*/

public final class AlreadyInLotExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public ParkNPark.interfaces.AlreadyInLotException value = null;

  public AlreadyInLotExceptionHolder ()
  {
  }

  public AlreadyInLotExceptionHolder (ParkNPark.interfaces.AlreadyInLotException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ParkNPark.interfaces.AlreadyInLotExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ParkNPark.interfaces.AlreadyInLotExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ParkNPark.interfaces.AlreadyInLotExceptionHelper.type ();
  }

}
