package ParkNPark.interfaces;


/**
* ParkNPark/interfaces/AtBottomLevelException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:36 PM EDT
*/

public final class AtBottomLevelException extends org.omg.CORBA.UserException
{

  /** The lot that contains the level */
  public int lot = (int)0;

  /** The level that is the lowest level of the lot */
  public int level = (int)0;

  public AtBottomLevelException ()
  {
    super(AtBottomLevelExceptionHelper.id());
  } // ctor

  public AtBottomLevelException (int _lot, int _level)
  {
    super(AtBottomLevelExceptionHelper.id());
    lot = _lot;
    level = _level;
  } // ctor


  public AtBottomLevelException (String $reason, int _lot, int _level)
  {
    super(AtBottomLevelExceptionHelper.id() + "  " + $reason);
    lot = _lot;
    level = _level;
  } // ctor

} // class AtBottomLevelException
