package ParkNPark.interfaces;

/**
* ParkNPark/interfaces/AtBottomLevelExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:36 PM EDT
*/

public final class AtBottomLevelExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public ParkNPark.interfaces.AtBottomLevelException value = null;

  public AtBottomLevelExceptionHolder ()
  {
  }

  public AtBottomLevelExceptionHolder (ParkNPark.interfaces.AtBottomLevelException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ParkNPark.interfaces.AtBottomLevelExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ParkNPark.interfaces.AtBottomLevelExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ParkNPark.interfaces.AtBottomLevelExceptionHelper.type ();
  }

}
