package ParkNPark.interfaces;

/**
* ParkNPark/interfaces/AtTopLevelExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:35 PM EDT
*/

public final class AtTopLevelExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public ParkNPark.interfaces.AtTopLevelException value = null;

  public AtTopLevelExceptionHolder ()
  {
  }

  public AtTopLevelExceptionHolder (ParkNPark.interfaces.AtTopLevelException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ParkNPark.interfaces.AtTopLevelExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ParkNPark.interfaces.AtTopLevelExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ParkNPark.interfaces.AtTopLevelExceptionHelper.type ();
  }

}
