package ParkNPark.interfaces;


/**
* ParkNPark/interfaces/AtTopLevelExceptionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:35 PM EDT
*/

abstract public class AtTopLevelExceptionHelper
{
  private static String  _id = "IDL:ParkNPark/interfaces/AtTopLevelException:1.0";

  public static void insert (org.omg.CORBA.Any a, ParkNPark.interfaces.AtTopLevelException that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ParkNPark.interfaces.AtTopLevelException extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "lot",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "level",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (ParkNPark.interfaces.AtTopLevelExceptionHelper.id (), "AtTopLevelException", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ParkNPark.interfaces.AtTopLevelException read (org.omg.CORBA.portable.InputStream istream)
  {
    ParkNPark.interfaces.AtTopLevelException value = new ParkNPark.interfaces.AtTopLevelException ();
    // read and discard the repository ID
    istream.read_string ();
    value.lot = istream.read_long ();
    value.level = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ParkNPark.interfaces.AtTopLevelException value)
  {
    // write the repository ID
    ostream.write_string (id ());
    ostream.write_long (value.lot);
    ostream.write_long (value.level);
  }

}
