package ParkNPark.interfaces;


/**
* ParkNPark/interfaces/AtTopLevelException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:36 PM EDT
*/

public final class AtTopLevelException extends org.omg.CORBA.UserException
{

  /** The lot that contains the level */
  public int lot = (int)0;

  /** The level that is the highest level of the lot */
  public int level = (int)0;

  public AtTopLevelException ()
  {
    super(AtTopLevelExceptionHelper.id());
  } // ctor

  public AtTopLevelException (int _lot, int _level)
  {
    super(AtTopLevelExceptionHelper.id());
    lot = _lot;
    level = _level;
  } // ctor


  public AtTopLevelException (String $reason, int _lot, int _level)
  {
    super(AtTopLevelExceptionHelper.id() + "  " + $reason);
    lot = _lot;
    level = _level;
  } // ctor

} // class AtTopLevelException
