package ParkNPark.interfaces;

/**
* ParkNPark/interfaces/ClientManagerFactoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:36 PM EDT
*/


/**
         * The main interface that the client uses to communicate with the server
         */
public final class ClientManagerFactoryHolder implements org.omg.CORBA.portable.Streamable
{
  public ParkNPark.interfaces.ClientManagerFactory value = null;

  public ClientManagerFactoryHolder ()
  {
  }

  public ClientManagerFactoryHolder (ParkNPark.interfaces.ClientManagerFactory initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ParkNPark.interfaces.ClientManagerFactoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ParkNPark.interfaces.ClientManagerFactoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ParkNPark.interfaces.ClientManagerFactoryHelper.type ();
  }

}
