package ParkNPark.interfaces;


/**
* ParkNPark/interfaces/ClientManagerFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:36 PM EDT
*/


/**
         * The main interface that the client uses to communicate with the server
         */
public interface ClientManagerFactory extends ClientManagerFactoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientManagerFactory
