package ParkNPark.interfaces;

/**
* ParkNPark/interfaces/ClientManagerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:36 PM EDT
*/


/**
         * The interface that a single client uses to communicate with its server-side
         * client manager instance
         */
public final class ClientManagerHolder implements org.omg.CORBA.portable.Streamable
{
  public ParkNPark.interfaces.ClientManager value = null;

  public ClientManagerHolder ()
  {
  }

  public ClientManagerHolder (ParkNPark.interfaces.ClientManager initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ParkNPark.interfaces.ClientManagerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ParkNPark.interfaces.ClientManagerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ParkNPark.interfaces.ClientManagerHelper.type ();
  }

}
