package ParkNPark.interfaces;


/**
* ParkNPark/interfaces/InvalidSequenceNumberException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:35 PM EDT
*/


/**
         * Thrown when the client's sequence number is less than what the server expected
         * [Category: Dependability; Requirement: 2]
         */
public final class InvalidSequenceNumberException extends org.omg.CORBA.UserException
{

  /** ID of the client */
  public int clientID = (int)0;

  /** Sequence number that is not valid */
  public int seq = (int)0;

  public InvalidSequenceNumberException ()
  {
    super(InvalidSequenceNumberExceptionHelper.id());
  } // ctor

  public InvalidSequenceNumberException (int _clientID, int _seq)
  {
    super(InvalidSequenceNumberExceptionHelper.id());
    clientID = _clientID;
    seq = _seq;
  } // ctor


  public InvalidSequenceNumberException (String $reason, int _clientID, int _seq)
  {
    super(InvalidSequenceNumberExceptionHelper.id() + "  " + $reason);
    clientID = _clientID;
    seq = _seq;
  } // ctor

} // class InvalidSequenceNumberException
