package ParkNPark.interfaces;

/**
* ParkNPark/interfaces/InvalidSequenceNumberExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:35 PM EDT
*/


/**
         * Thrown when the client's sequence number is less than what the server expected
         * [Category: Dependability; Requirement: 2]
         */
public final class InvalidSequenceNumberExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public ParkNPark.interfaces.InvalidSequenceNumberException value = null;

  public InvalidSequenceNumberExceptionHolder ()
  {
  }

  public InvalidSequenceNumberExceptionHolder (ParkNPark.interfaces.InvalidSequenceNumberException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ParkNPark.interfaces.InvalidSequenceNumberExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ParkNPark.interfaces.InvalidSequenceNumberExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ParkNPark.interfaces.InvalidSequenceNumberExceptionHelper.type ();
  }

}
