package ParkNPark.interfaces;

/**
* ParkNPark/interfaces/InvalidClientExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:35 PM EDT
*/

public final class InvalidClientExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public ParkNPark.interfaces.InvalidClientException value = null;

  public InvalidClientExceptionHolder ()
  {
  }

  public InvalidClientExceptionHolder (ParkNPark.interfaces.InvalidClientException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ParkNPark.interfaces.InvalidClientExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ParkNPark.interfaces.InvalidClientExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ParkNPark.interfaces.InvalidClientExceptionHelper.type ();
  }

}
