package ParkNPark.interfaces;


/**
* ParkNPark/interfaces/LongSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:35 PM EDT
*/


/**
         * CORBA type for an integer array
         */
public final class LongSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public LongSeqHolder ()
  {
  }

  public LongSeqHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ParkNPark.interfaces.LongSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ParkNPark.interfaces.LongSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ParkNPark.interfaces.LongSeqHelper.type ();
  }

}
