package ParkNPark.interfaces;


/**
* ParkNPark/interfaces/LotFullException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:35 PM EDT
*/

public final class LotFullException extends org.omg.CORBA.UserException
{

  /** The capacity of the lot */
  public int lotCapacity = (int)0;

  /** The lot that is full */
  public int lot = (int)0;

  public LotFullException ()
  {
    super(LotFullExceptionHelper.id());
  } // ctor

  public LotFullException (int _lotCapacity, int _lot)
  {
    super(LotFullExceptionHelper.id());
    lotCapacity = _lotCapacity;
    lot = _lot;
  } // ctor


  public LotFullException (String $reason, int _lotCapacity, int _lot)
  {
    super(LotFullExceptionHelper.id() + "  " + $reason);
    lotCapacity = _lotCapacity;
    lot = _lot;
  } // ctor

} // class LotFullException
