package ParkNPark.interfaces;


/**
* ParkNPark/interfaces/LotNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:35 PM EDT
*/

public final class LotNotFoundException extends org.omg.CORBA.UserException
{

  /** The lot number that was not found in the system */
  public int lot = (int)0;

  public LotNotFoundException ()
  {
    super(LotNotFoundExceptionHelper.id());
  } // ctor

  public LotNotFoundException (int _lot)
  {
    super(LotNotFoundExceptionHelper.id());
    lot = _lot;
  } // ctor


  public LotNotFoundException (String $reason, int _lot)
  {
    super(LotNotFoundExceptionHelper.id() + "  " + $reason);
    lot = _lot;
  } // ctor

} // class LotNotFoundException
