package ParkNPark.interfaces;

/**
* ParkNPark/interfaces/NotInLotExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:36 PM EDT
*/

public final class NotInLotExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public ParkNPark.interfaces.NotInLotException value = null;

  public NotInLotExceptionHolder ()
  {
  }

  public NotInLotExceptionHolder (ParkNPark.interfaces.NotInLotException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ParkNPark.interfaces.NotInLotExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ParkNPark.interfaces.NotInLotExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ParkNPark.interfaces.NotInLotExceptionHelper.type ();
  }

}
