package ParkNPark.interfaces;


/**
* ParkNPark/interfaces/NotOnExitLevelException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:36 PM EDT
*/

public final class NotOnExitLevelException extends org.omg.CORBA.UserException
{

  /** The lot that the level is in */
  public int lot = (int)0;

  /** The current level */
  public int level = (int)0;

  public NotOnExitLevelException ()
  {
    super(NotOnExitLevelExceptionHelper.id());
  } // ctor

  public NotOnExitLevelException (int _lot, int _level)
  {
    super(NotOnExitLevelExceptionHelper.id());
    lot = _lot;
    level = _level;
  } // ctor


  public NotOnExitLevelException (String $reason, int _lot, int _level)
  {
    super(NotOnExitLevelExceptionHelper.id() + "  " + $reason);
    lot = _lot;
    level = _level;
  } // ctor

} // class NotOnExitLevelException
