package ParkNPark.interfaces;

/**
* ParkNPark/interfaces/NotOnExitLevelExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:36 PM EDT
*/

public final class NotOnExitLevelExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public ParkNPark.interfaces.NotOnExitLevelException value = null;

  public NotOnExitLevelExceptionHolder ()
  {
  }

  public NotOnExitLevelExceptionHolder (ParkNPark.interfaces.NotOnExitLevelException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ParkNPark.interfaces.NotOnExitLevelExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ParkNPark.interfaces.NotOnExitLevelExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ParkNPark.interfaces.NotOnExitLevelExceptionHelper.type ();
  }

}
