package ParkNPark.interfaces;

/**
* ParkNPark/interfaces/PaddedVoidHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:35 PM EDT
*/

public final class PaddedVoidHolder implements org.omg.CORBA.portable.Streamable
{
  public ParkNPark.interfaces.PaddedVoid value = null;

  public PaddedVoidHolder ()
  {
  }

  public PaddedVoidHolder (ParkNPark.interfaces.PaddedVoid initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ParkNPark.interfaces.PaddedVoidHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ParkNPark.interfaces.PaddedVoidHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ParkNPark.interfaces.PaddedVoidHelper.type ();
  }

}
