package ParkNPark.interfaces;

/**
* ParkNPark/interfaces/PaddedIntegerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:35 PM EDT
*/

public final class PaddedIntegerHolder implements org.omg.CORBA.portable.Streamable
{
  public ParkNPark.interfaces.PaddedInteger value = null;

  public PaddedIntegerHolder ()
  {
  }

  public PaddedIntegerHolder (ParkNPark.interfaces.PaddedInteger initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ParkNPark.interfaces.PaddedIntegerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ParkNPark.interfaces.PaddedIntegerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ParkNPark.interfaces.PaddedIntegerHelper.type ();
  }

}
