package ParkNPark.interfaces;

/**
* ParkNPark/interfaces/PaddedIntegerSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:35 PM EDT
*/

public final class PaddedIntegerSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public ParkNPark.interfaces.PaddedIntegerSeq value = null;

  public PaddedIntegerSeqHolder ()
  {
  }

  public PaddedIntegerSeqHolder (ParkNPark.interfaces.PaddedIntegerSeq initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ParkNPark.interfaces.PaddedIntegerSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ParkNPark.interfaces.PaddedIntegerSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ParkNPark.interfaces.PaddedIntegerSeqHelper.type ();
  }

}
