package ParkNPark.interfaces;


/**
* ParkNPark/interfaces/PaddedIntegerSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:35 PM EDT
*/

abstract public class PaddedIntegerSeqHelper
{
  private static String  _id = "IDL:ParkNPark/interfaces/PaddedIntegerSeq/PaddedIntegerSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, ParkNPark.interfaces.PaddedIntegerSeq that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ParkNPark.interfaces.PaddedIntegerSeq extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ParkNPark.interfaces.LongSeqHelper.id (), "LongSeq", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "value",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (ParkNPark.interfaces.ByteSeqHelper.id (), "ByteSeq", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "padding",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ParkNPark.interfaces.PaddedIntegerSeqHelper.id (), "PaddedIntegerSeq", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ParkNPark.interfaces.PaddedIntegerSeq read (org.omg.CORBA.portable.InputStream istream)
  {
    ParkNPark.interfaces.PaddedIntegerSeq value = new ParkNPark.interfaces.PaddedIntegerSeq ();
    value.value = ParkNPark.interfaces.LongSeqHelper.read (istream);
    value.padding = ParkNPark.interfaces.ByteSeqHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ParkNPark.interfaces.PaddedIntegerSeq value)
  {
    ParkNPark.interfaces.LongSeqHelper.write (ostream, value.value);
    ParkNPark.interfaces.ByteSeqHelper.write (ostream, value.padding);
  }

}
