package ParkNPark.interfaces;


/**
* ParkNPark/interfaces/PaddedIntegerSeq.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:35 PM EDT
*/

public final class PaddedIntegerSeq implements org.omg.CORBA.portable.IDLEntity
{

  /** The integer array that we care about */
  public int value[] = null;

  /** The padding */
  public byte padding[] = null;

  public PaddedIntegerSeq ()
  {
  } // ctor

  public PaddedIntegerSeq (int[] _value, byte[] _padding)
  {
    value = _value;
    padding = _padding;
  } // ctor

} // class PaddedIntegerSeq
