package ParkNPark.interfaces;


/**
* ParkNPark/interfaces/PaddedInteger.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:35 PM EDT
*/

public final class PaddedInteger implements org.omg.CORBA.portable.IDLEntity
{

  /** The integer that we care about */
  public int value = (int)0;

  /** The padding */
  public byte padding[] = null;

  public PaddedInteger ()
  {
  } // ctor

  public PaddedInteger (int _value, byte[] _padding)
  {
    value = _value;
    padding = _padding;
  } // ctor

} // class PaddedInteger
