package ParkNPark.interfaces;


/**
* ParkNPark/interfaces/PaddedVoid.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:35 PM EDT
*/

public final class PaddedVoid implements org.omg.CORBA.portable.IDLEntity
{

  /** The padding */
  public byte padding[] = null;

  public PaddedVoid ()
  {
  } // ctor

  public PaddedVoid (byte[] _padding)
  {
    padding = _padding;
  } // ctor

} // class PaddedVoid
