package ParkNPark.interfaces;


/**
* ParkNPark/interfaces/ReplicationManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:36 PM EDT
*/

public interface ReplicationManager extends ReplicationManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ReplicationManager
