package ParkNPark.interfaces;


/**
* ParkNPark/interfaces/ReplicationManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:36 PM EDT
*/

public interface ReplicationManagerOperations 
{
  void serverRegistered (String ipAddress, String serviceName, ParkNPark.interfaces.ClientManagerFactory cmf);
} // interface ReplicationManagerOperations
