package ParkNPark.interfaces;


/**
* ParkNPark/interfaces/ReplicationManagerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:36 PM EDT
*/

abstract public class ReplicationManagerHelper
{
  private static String  _id = "IDL:ParkNPark/interfaces/ReplicationManager:1.0";

  public static void insert (org.omg.CORBA.Any a, ParkNPark.interfaces.ReplicationManager that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ParkNPark.interfaces.ReplicationManager extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ParkNPark.interfaces.ReplicationManagerHelper.id (), "ReplicationManager");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ParkNPark.interfaces.ReplicationManager read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ReplicationManagerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ParkNPark.interfaces.ReplicationManager value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ParkNPark.interfaces.ReplicationManager narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ParkNPark.interfaces.ReplicationManager)
      return (ParkNPark.interfaces.ReplicationManager)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ParkNPark.interfaces._ReplicationManagerStub stub = new ParkNPark.interfaces._ReplicationManagerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ParkNPark.interfaces.ReplicationManager unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ParkNPark.interfaces.ReplicationManager)
      return (ParkNPark.interfaces.ReplicationManager)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ParkNPark.interfaces._ReplicationManagerStub stub = new ParkNPark.interfaces._ReplicationManagerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
