package ParkNPark.interfaces;


/**
* ParkNPark/interfaces/ServiceUnavailableExceptionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:36 PM EDT
*/

abstract public class ServiceUnavailableExceptionHelper
{
  private static String  _id = "IDL:ParkNPark/interfaces/ServiceUnavailableException:1.0";

  public static void insert (org.omg.CORBA.Any a, ParkNPark.interfaces.ServiceUnavailableException that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ParkNPark.interfaces.ServiceUnavailableException extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "message",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (ParkNPark.interfaces.ServiceUnavailableExceptionHelper.id (), "ServiceUnavailableException", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ParkNPark.interfaces.ServiceUnavailableException read (org.omg.CORBA.portable.InputStream istream)
  {
    ParkNPark.interfaces.ServiceUnavailableException value = new ParkNPark.interfaces.ServiceUnavailableException ();
    // read and discard the repository ID
    istream.read_string ();
    value.message = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ParkNPark.interfaces.ServiceUnavailableException value)
  {
    // write the repository ID
    ostream.write_string (id ());
    ostream.write_string (value.message);
  }

}
