package ParkNPark.interfaces;

/**
* ParkNPark/interfaces/ServiceUnavailableExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:36 PM EDT
*/

public final class ServiceUnavailableExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public ParkNPark.interfaces.ServiceUnavailableException value = null;

  public ServiceUnavailableExceptionHolder ()
  {
  }

  public ServiceUnavailableExceptionHolder (ParkNPark.interfaces.ServiceUnavailableException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ParkNPark.interfaces.ServiceUnavailableExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ParkNPark.interfaces.ServiceUnavailableExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ParkNPark.interfaces.ServiceUnavailableExceptionHelper.type ();
  }

}
