package ParkNPark.interfaces;


/**
* ParkNPark/interfaces/ServiceUnavailableException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Friday, May 5, 2006 10:19:36 PM EDT
*/

public final class ServiceUnavailableException extends org.omg.CORBA.UserException
{

  /** Error message for the client */
  public String message = null;

  public ServiceUnavailableException ()
  {
    super(ServiceUnavailableExceptionHelper.id());
  } // ctor

  public ServiceUnavailableException (String _message)
  {
    super(ServiceUnavailableExceptionHelper.id());
    message = _message;
  } // ctor


  public ServiceUnavailableException (String $reason, String _message)
  {
    super(ServiceUnavailableExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class ServiceUnavailableException
